//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CleanProcedure
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clean_Record
    {
        public int ID { get; set; }
        public string CleanID { get; set; }
        public string CardIp { get; set; }
        public string CleanGroup { get; set; }
        public string CardID { get; set; }
        public string CardName { get; set; }
        public string MarrorID { get; set; }
        public string MarrorName { get; set; }
        public string CleanType { get; set; }
        public string CleanStatus { get; set; }
        public Nullable<System.DateTime> CleanCreateTime { get; set; }
        public string CleanDate { get; set; }
        public string NowStep { get; set; }
        public string NowStepName { get; set; }
        public string NowStepTime { get; set; }
        public Nullable<System.DateTime> CleanStart { get; set; }
        public Nullable<System.DateTime> CleanStop { get; set; }
        public string CleanTime { get; set; }
        public string CleanCardName { get; set; }
        public string CleanDetail { get; set; }
        public string CleanAllTime { get; set; }
        public string UseStatus { get; set; }
        public string ZuofeiID { get; set; }
        public string ZuofeiTime { get; set; }
        public string Endoscopic { get; set; }
        public string PatientID { get; set; }
        public string PatientName { get; set; }
        public string Sex { get; set; }
        public string Age { get; set; }
        public string ExamRoom { get; set; }
        public string ExamDoctor { get; set; }
        public string ExamNurse { get; set; }
        public string ExamDate { get; set; }
        public string ExamTime { get; set; }
        public string ExamComputer { get; set; }
        public string ReportDoctor { get; set; }
        public string HP { get; set; }
        public string Negative { get; set; }
        public string Report { get; set; }
        public string Remark { get; set; }
        public string SevereTag { get; set; }
        public string OtherInfect { get; set; }
        public bool MarrorStatus { get; set; }
        public string MarrorType { get; set; }
        public string MarrorCleanPerson { get; set; }
    }
}
