//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CleanProcedure
{
    using System;
    using System.Collections.Generic;
    
    public partial class CleanCard_UserList
    {
        public int id { get; set; }
        public string CleanCard { get; set; }
        public int Sequence { get; set; }
        public string UseStatus { get; set; }
        public string ZuofeiID { get; set; }
        public Nullable<System.DateTime> ZuofeiTime { get; set; }
        public string Endoscopic { get; set; }
        public string PatientID { get; set; }
        public string PatientName { get; set; }
        public string Sex { get; set; }
        public string Age { get; set; }
        public string ExamRoom { get; set; }
        public string ExamDoctor { get; set; }
        public string ExamNurse { get; set; }
        public Nullable<System.DateTime> ExamTime { get; set; }
    }
}
