//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CleanProcedure
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clean_RecordList
    {
        public int Id { get; set; }
        public string CleanCard { get; set; }
        public string CleanIp { get; set; }
        public System.DateTime StartTime { get; set; }
        public string CleanPort { get; set; }
        public int StepTime { get; set; }
        public string StepName { get; set; }
        public int StepNum { get; set; }
        public int MaxNum { get; set; }
    }
}
