//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CleanProcedure
{
    using System;
    using System.Collections.Generic;
    
    public partial class CleanListView
    {
        public int Sequence { get; set; }
        public string CleanCard { get; set; }
        public string WorkCard { get; set; }
        public string cleanprc { get; set; }
    }
}
