//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CleanProcedure
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CleanProcedureEntities : DbContext
    {
        public CleanProcedureEntities()
            : base("name=CleanProcedureEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Clean_Card> Clean_Card { get; set; }
        public DbSet<Clean_Factory> Clean_Factory { get; set; }
        public DbSet<Clean_Pretreatment> Clean_Pretreatment { get; set; }
        public DbSet<Clean_Record> Clean_Record { get; set; }
        public DbSet<Clean_RecordList> Clean_RecordList { get; set; }
        public DbSet<Dic_Area> Dic_Area { get; set; }
        public DbSet<Dic_UserRole> Dic_UserRole { get; set; }
        public DbSet<Dic_Workgroup> Dic_Workgroup { get; set; }
        public DbSet<Endoscopic_Device> Endoscopic_Device { get; set; }
        public DbSet<Endoscopic_Mirror> Endoscopic_Mirror { get; set; }
        public DbSet<Clean_CardDevice> Clean_CardDevice { get; set; }
        public DbSet<Clean_User> Clean_User { get; set; }
        public DbSet<CleanListView> CleanListView { get; set; }
        public DbSet<CleanCard_UserList> CleanCard_UserList { get; set; }
    }
}
