//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CleanProcedure
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clean_Card
    {
        public int ID { get; set; }
        public string CardNo { get; set; }
        public string DevType { get; set; }
        public string CardID { get; set; }
        public string CardName { get; set; }
        public string CardType { get; set; }
        public string Department { get; set; }
        public string ExamRoom { get; set; }
        public string Uses { get; set; }
        public string StartedDate { get; set; }
        public bool Stopped { get; set; }
        public string StoppedDate { get; set; }
        public string StopReason { get; set; }
        public string HandlingMan { get; set; }
        public string DevRemark { get; set; }
    }
}
