//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CleanProcedure
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clean_CardDevice
    {
        public int ID { get; set; }
        public string CardNo { get; set; }
        public string CardName { get; set; }
        public string DevType { get; set; }
        public Nullable<short> StepCount { get; set; }
        public Nullable<short> StepNumber { get; set; }
        public string StepName { get; set; }
        public string StepTime { get; set; }
        public string StepType { get; set; }
        public Nullable<short> LastStepNumber { get; set; }
        public string LastStepName { get; set; }
        public string LastStepTime { get; set; }
        public string DeviceName { get; set; }
        public string ClientIP { get; set; }
        public string ClientPort { get; set; }
        public string WorkStationIP { get; set; }
        public string CleanID { get; set; }
        public string ServerIp { get; set; }
        public string ServerPort { get; set; }
        public string CleanGroup { get; set; }
        public string StartedDate { get; set; }
        public Nullable<bool> Stopped { get; set; }
        public string StoppedDate { get; set; }
        public string StopReason { get; set; }
        public string HandlingMan { get; set; }
        public string MsgIp { get; set; }
        public string Remark { get; set; }
        public string MarrorID { get; set; }
        public string MarrorName { get; set; }
        public string MarrorType { get; set; }
    }
}
