//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CleanProcedure
{
    using System;
    using System.Collections.Generic;
    
    public partial class Endoscopic_Mirror
    {
        public int ID { get; set; }
        public string MirrorID { get; set; }
        public string MirrorCardID { get; set; }
        public string DevName { get; set; }
        public string DevFac { get; set; }
        public string Department { get; set; }
        public string ExamRoom { get; set; }
        public string Uses { get; set; }
        public string DevRemark { get; set; }
    }
}
